Update switchbot_util.py
My device settings:
`{'battery': 94, 'firmware': 6.4, 'n_timers': 0, 'dual_state_mode': True, 'inverse_direction': True, 'hold_seconds': 0}`

 
` File "/usr/lib/python3.11/enum.py", line 717, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1133, in __new__
    raise ve_exc
ValueError: 5 is not a valid ActionStatus`

I did a little bit of research and came across:

- 0x05 - Device does not support this Command